[provider]
# Smartsim default parameters: std::string host = "localhost", int port = 6379, int nodes = 1, int tasks_per_node = 1, int cpus_per_task = 1, int gpus_per_task = 0
name = "Smartsim"
port = 6379
host = "localhost"
nodes = 2
tasks_per_node = 4
cpus_per_task = 2
gpus_per_task = 0

[normalization]
name="minmax"
input_min=-1.0
input_max=1.0
output_min=0.0
output_max=1.0

[dataprocessor]
name="MLCouplingDataProcessorSimple"

[behavior]
name="MLCouplingBehaviorDefault"

[application]
name="MLCouplingApplicationTurbulenceClosure"